### ISSUE TITLE
Vaccinee Plasma Susceptibility Data: no way to sort by organism

### ISSUE THREAD

**Issue by acwalls** [hivdb/chiro-frontend#13]
It would be great to list the organism these results come from (i.e. mouse, NHP, or human) since currently it requires checking each paper figure

**Comment by rshaferw** [comment]
> It would be great to list the organism these results come from (i.e. mouse, NHP, or human) since currently it requires checking each paper figure
We are currently storing that data but not yet displaying it. That said nearly all of the data so far are from human samples. We do plan to indicate the source soon as an increasing amount of data are from vaccinated animals.

**Comment by philiptzou** [comment]
@acwalls Thanks for the suggestion! We'll definitely add the hostSpecies to our table display.

**Comment by philiptzou** [comment]
@acwalls Thanks for the suggestion! We have added the "Host" column to our table. Here is an example.

https://user-images.githubusercontent.com/809865/132958063-43171f22-07f3-4b76-ad61-254c512e4c98.mp4
