### ISSUE TITLE
Geomean value error

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/chiro-frontend#22]
Ref: Barouch21
rx: Ad26.COV2.S 1dose 1month
iso_name: Alpha
num results: 10

manual calculated geomean: 99.9
js function aggGeoMeanWeighted calculated geomean: 99.9

web page value: 87

https://covdb.stanford.edu/search-drdb/?vaccine=Ad26.COV2.S&variant=Alpha

**Comment by philiptzou** [comment]
Won't fix. This is an expected results of hivdb/covid-drdb-payload#55. For Ad26_1dose_d29_4 and Ad26_1dose_d29_8, both <20 titers were included in the calculation as 10. After replacing the two 20 to 10, the GeoMean is exact 87.

<img width="250" alt="Screen Shot 2021-09-23 at 2 50 25 PM" src="https://user-images.githubusercontent.com/809865/134588901-ad95360c-87eb-43bd-9438-292ffd815143.png">
