### ISSUE TITLE
fold reduction median accuracy

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/chiro-frontend#41]
- if the `fold_cmp` is not `=`, use integer
- if the `fold_cmp` is larger than 10, use integer

**Comment by philiptzou** [comment]
What is this?

**Comment by KaimingTao** [comment]
Change the representation of fold

> What is this?

Changing the accuracy we shown for the fold reduction.

**Comment by KaimingTao** [comment]
<img width="132" alt="Screen Shot 2022-01-03 at 14 53 06" src="https://user-images.githubusercontent.com/988193/147989032-2c7030b0-e361-4aab-a83b-58dd076eec42.png">

**Comment by philiptzou** [comment]
Oh you mean when we used `>` or `<` symbol, or when the number is greater than 10, the number should be integer?
