### ISSUE TITLE
In vitro, in vivo and DMS data should be only filtered by individual mutations, not by patterns or by variants

### ISSUE THREAD

**Issue by rshaferw** [hivdb/chiro-frontend#47]
See the attached screen shot or run the query with Cele2001b alone or Cele2001b plus omicron. This should not be linked to omicron.

<img width="1379" alt="Screen Shot 2021-12-30 at 1 19 41 PM" src="https://user-images.githubusercontent.com/8672489/147788678-4085a287-7f81-4a14-9244-4202e1c2c145.png">

**Comment by philiptzou** [comment]
Moved from hivdb/covid-drdb-payload since this is actually a frontend issue. The 3 results of Cele21b are in vivo data which have mutations of Omicron. As per our previous oral discussion, in vitro, in vivo and DMS data will be only filtered by individual mutations but not patterns or variants.
