### ISSUE TITLE
Please add "Variant: Mutations" back into csv file (feedback from MacGregorCox)

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/chiro-frontend#53]
This issue is forward from https://github.com/hivdb/covid-drdb-payload/commit/e74a8f342f7152c003ae87977057a8a73bd5c753

> Sorry this is probably not the correct thread. But I could not find the log for the change I am talking about.
> 
> I am working with the mAb susceptability Excel/ CSV download. On 24th Dec this contain a column "Variant: Mutations" at column 13. But now this column does not exist. This was very useful, as I am trying to split the data by the Omicron subvariants (BA.1, BA.2, BA.1.1. etc). Given the rapid changes in frequency of these different variants, especially the rapid expansion of BA.2 in some european countries, it is worth considering splitting Omicron into these sub lineages.
> 
> Many thanks,
> Mac

**Comment by philiptzou** [comment]
To be clear, this request is trying to revert #44. @rshaferw @KaimingTao please confirm.

**Comment by KaimingTao** [comment]
@MacGregorCox, this issue is fixed.

**Comment by MacGregorCox** [comment]
Great, thank you for this. I think this will be very useful as the different sublineages of Omicron begin to be studied
